from flask import Flask, render_template, request, flash, redirect, url_for
from sqlalchemy import create_engine
from flask_login import login_user, logout_user, current_user, login_required,\
    LoginManager
from forms import SearchForm, MovieEntryForm

app = Flask(__name__)
app.secret_key = 'cse305'
engine = create_engine('postgresql://Elliot@localhost:5432/moviedb')
login = LoginManager(app)
login.login_view = 'login'

@app.route('/', methods=['GET', 'POST'])
@app.route('/index', methods=['GET', 'POST'])
def main():
    form = SearchForm(request.form)
    if request.method == 'POST' and form.validate():
        search_string = form.searchbar.data
        connection = engine.connect()
        query = "SELECT * FROM Movie WHERE LOWER(Name) LIKE '%%{}%%'".format(
            search_string.lower())
        result = connection.execute(query)
        movie_listing = []
        for row in result:
            movie_listing.append((row.id, row.name.strip()))
        return render_template('search_results.html',
                               movie_listing=movie_listing)
    return render_template("index.html", form=form)

@app.route('/enter_movie', methods=['GET', 'POST'])
def enter_movie():
    form = MovieEntryForm(request.form)
    if request.method == 'POST' and form.validate():
        name = form.name.data
        release_date = form.release_date.data if form.release_date.data \
            else 'NULL'
        duration = form.duration.data if form.duration.data else 'NULL'
        description = form.description.data
        budget = form.budget.data if form.budget.data else 'NULL'
        mpaa_rating = form.mpaa_rating.data if form.mpaa_rating.data \
            else 'NULL'
        genres = form.genres.data
        connection = engine.connect()
        # insert movie info into Movie table
        connection.execute("INSERT INTO Movie(Id, Name, ReleaseDate,"   \
                           "Duration, Description, Budget, MPAARating)" \
                           "VALUES (DEFAULT, '{}', '{}', {}, '{}', {}, '{}')".
                           format(name, release_date, duration, description,
                                  budget, mpaa_rating))
        # get Id generated by PostgreSQL
        rows = connection.execute("SELECT * FROM Movie WHERE Name = '{}' AND "\
                                 "ReleaseDate = '{}' AND Duration = '{}' AND "\
                                 "Description = '{}' AND Budget = '{}' AND "  \
                                 "MPAARating = '{}'".format(name, release_date,
                                                            duration,
                                                            description,
                                                            budget,
                                                            mpaa_rating))
        id_val = rows.fetchone()[0]
        # insert genres into MovieGenre table
        print(genres)
        for genre in genres:
            connection.execute("INSERT INTO MovieGenre(Id, Genre) VALUES ({},"\
                               "'{}')".format(id_val, genre))
        flash('Movie information successfully entered.')
        return redirect(url_for('main'))
    return render_template('enter_movie.html', form=form)

@app.route('/movie/<id_val>')
def show_movie_info(id_val):
    connection = engine.connect()
    result = connection.execute('SELECT * FROM Movie WHERE Id = {}'.format(
        id_val))
    movie_info = result.fetchone()
    return render_template('movie_info.html', movie_info=movie_info)
